; ========== GameBoost v1.1 ==========

[Processes]
LowPriority=Discord,DiscordPTB,DiscordCanary,chrome,msedge,brave,opera
HighPriority=cs2,csgo,valorant,RocketLeague,dota2,FortniteClient-Win64,eldenring,GTA5,apex,rustclient,League of Legends,Wow,Wow-64,Destiny2,Warframe
LowPriorityClass=BelowNormal
HighPriorityClass=High
ProcessCheckInterval=3
OnlyForegroundGame=0
TrimLowPriorityMemory=1

[Heroic]
HeroicMode=1
HeroicLauncherPriority=BelowNormal
HeroicSettingsBoost=1
HeroicGameProcesses=

[Hotkey]
HotkeyEnabled=1

[Optimizations]
ApplyOptimizations=1
OptimizationCheckInterval=10
PowerPlan=HighPerformance
DisableGameDVR=1
DisableFullscreenOptimizations=1
DisablePowerThrottling=1
NetworkThrottling=1
DisableNagle=1
TimerResolution=1
GameTaskPriority=1
HardwareGPU=0

[General]
EnableLog=0
LogPath=